services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - skeevy-data:/data/db
  backend:
    build: ./backend
    environment:
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
volumes:
  skeevy-data:
