services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    restart: always
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    restart: always
volumes:
  data:
